pipeline {
   agent any

   tools {
      maven 'maven 3.6.1'
   }

   stages {
      stage('build') {
         steps {
            echo 'compling users service'
            dir('java/cmad-ms-users') {
               sh 'mvn compile'
            }
         }
      }
      
      stage('test') {
         steps {
            echo 'running unit tests on users service'
            dir('java/cmad-ms-users') {
               sh 'mvn clean test'
            }
         }
      }
      
      stage('package') {
         steps {
            echo 'packaging users app'
            dir('java/cmad-ms-users') {
               sh 'mvn package -DskipTests'
            }
         }
      }
   }
}